name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    - develop

jobs:
  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        runs-on: [ubuntu-latest, macos-latest]


    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install .[test]

    - name: Test package
      run: python -m pytest -ra --cov-report=xml

    - name: Upload coverage to codecov
      if: matrix.python-version == 3.7
        uses: codecov/codecov-action@v1
        with:
          #token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
